services:
  postgres:
    image: postgres:16
    container_name: postgres_gerenciador_frota
    restart: always
    environment:
      POSTGRES_USER: gerenciador_frota_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gerenciador_frota
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gerenciador_frota
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@reserva.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
