services:
  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: postgres_gerenciador_frota
    restart: always
    environment:
      POSTGRES_USER: gerenciador_frota_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gerenciador_frota
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gerenciador_frota
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@reserva.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - dcs-postgres

networks:
  default:
    name: local-network
    external: true
